### ISSUE TITLE
Sorry to bother you again. 

### ISSUE THREAD

**Issue by c1a1o1** [yabufarha/anticipating-activities#3]
Sorry to bother you again. I tried it all day, but did not achieve the effect of your video. Can you give me more guidance?

**Comment by yabufarha** [comment]
The code provided generates frame-wise action labels. To overlay these labels to the video, we wrote a small python script.

**Comment by c1a1o1** [comment]
Can you share the small script?I tried all three days and failed

**Comment by c1a1o1** [comment]
My email: c1a1o1@qq.com 
Thank you very much !
It is a great work!

**Comment by c1a1o1** [comment]
I can overlay these labels, but I can't  generate videos like your best video in youtube!
