### ISSUE TITLE
Running without GT observations

### ISSUE THREAD

**Issue by ClaraBing** [yabufarha/anticipating-activities#4]
Hi Yazan,

Thank you so much for sharing the code! I used the model on our dataset with GT observations and it works great!

May I ask if there are also code for running the model without GT observations? Thank you very much!

**Comment by yabufarha** [comment]
Hi,

Happy that you found the code helpful. For running the code without GT observations, we used the model from https://github.com/alexanderrichard/squirrel to get the predicted action labels of the observed part and then run our trained model with these labels. The code is in examples/cvpr2017
Note that this model is for weakly supervised case but we train it fully supervised.
Related publications:
Richard et al. Weakly Supervised Action Learning with RNN based Fine-to-coarse Modeling. CVPR 2017
Kuehne et al. A Hybrid RNN-HMM Approach for Weakly Supervised Temporal Action Segmentation. PAMI 2019
