### ISSUE TITLE
Activities on the 50 Salads dataset

### ISSUE THREAD

**Issue by RomeroBarata** [yabufarha/anticipating-activities#6]
Dear @yabufarha ,

In the paper you describe that the 50 Salads dataset contains 17 actions. However, looking at the 50 Salads description I see that each action has 3 phases (pre-, core- and post-), which we could then be interpreted as 51 actions. In your experiments, did you consider the phases separately (51 actions) or grouped then together into a single action (17 actions)? Thanks for your attention.

Kind regards,
Romero

**Comment by yabufarha** [comment]
Hi Romero,

We used what is called mid-level annotations. Which means the 3 phases (pre-, core- and post-) are grouped into a single action resulting in 17 action classes in total.

Best,
Yazan

**Comment by RomeroBarata** [comment]
Hi Yazan,

Thanks for the clarification! Also, did you consider an extra silence/background action for the segments that are not annotated?

Regards,
Romero

**Comment by yabufarha** [comment]
Yes, we have background segments at the beginning and the end of the videos. But generally speaking, these segments are outside the predicted horizon, given the used observation-prediction percentages in our setup.

**Comment by RomeroBarata** [comment]
True, the background segment is outside the predicted horizon, but you would still have a background segment in the input part, right?

**Comment by yabufarha** [comment]
Yes, that's right. We still have these background segments.

**Comment by RomeroBarata** [comment]
Thank you for the clarifications Yazan!
