### ISSUE TITLE
parameters for 50Salads

### ISSUE THREAD

**Issue by suminlee94** [yabufarha/anticipating-activities#7]
Hi.
Thank you for publishing the codes.
I checked the performance on Breakfast, but I can't get to the reported performance on 50Salads.
Would you let me know parameters that you used for 50Salads in rnn version?
epoch, alpha, n_iterations, and etc.

Thank you.

**Comment by yabufarha** [comment]
Hi, 
alpha should be 20 for 50Salads.
For the other parameters, use the default values. However, I don't remember if the number of epochs is 15 or 20. Just make sure that the training converges.

**Comment by suminlee94** [comment]
Thank you!
